### ISSUE TITLE
can we get subscription id without setting the subscription schedule ?

### ISSUE THREAD

**Issue by mtariqsajid** [lbadmin/vendo-sdk-php#9]
Hi, 
when I send a request to
https://secure.vend-o.com/api/gateway/payment

without the subscription_schedule, the API response doesn't show the subscription id

is there a flag that I need to pass in order to get the subscription _id ?

**Comment by adolfoabegg** [comment]
Hello Tariq, yes, you must pass the subscription_schedule parameters in order to create a subscription
For example, if the amount is set to 30 and you want to create a monthly recurring billing with that same amount then you must to specify the `subscription_schedule` section like this

```
"subscription_schedule": {
        "rebill_duration": 30,
        "rebill_amount": 30.00
    },
```

**Comment by mtariqsajid** [comment]
> Hello Tariq, yes, you must pass the subscription_schedule parameters in order to create a subscription For example, if the amount is set to 30 and you want to create a monthly recurring billing with that same amount then you must to specify the `subscription_schedule` section like this
> 
> ```
> "subscription_schedule": {
>         "rebill_duration": 30,
>         "rebill_amount": 30.00
>     },
> ```

but if I don't want to pass the subscription schedule, then how to get the subscription id?

**Comment by adolfoabegg** [comment]
If you don't pass the subscription_schedule then 

- There's no subscription, no recurring payment will occur. 
- Our platform will perform a one-off payment. Subscription IDs are created for recurring schedules only.
- You will get the Transaction ID which you can use to issues refunds or search its details in Vendo's back office, see below:

```
{
    "status": 1,
    "external_references": {
        "transaction_reference": "example"
    },
    "transaction": {
        "id": 123456789,  <<---- This is the Vendo Transaction ID
        "amount": "30",
        "currency": "EUR",
        "datetime": "2022-09-14T18:42:12+02:00"
    },
    "card_details": {
        "auth_code": "123456e69c"
    },
    "payment_details_token": "xyzxyzxyzxyzxyzxyzxyz",
    "request_id": "yWaYwAyWaYwAyWaYwAyWaYwA"
}
```

**Comment by mtariqsajid** [comment]
> 

ok, thank you for your detailed response.

but I think the subscription should be returned anyway because when check-in Vendo dashboard I see that  Vendo is creating a subscription for that user. even if I don't send subscription schedule

**Comment by mtariqsajid** [comment]
> If you don't pass the subscription_schedule then
> 
> * There's no subscription, no recurring payment will occur.
> * Our platform will perform a one-off payment. Subscription IDs are created for recurring schedules only.
> * You will get the Transaction ID which you can use to issues refunds or search its details in Vendo's back office, see below:
> 
> ```
> {
>     "status": 1,
>     "external_references": {
>         "transaction_reference": "example"
>     },
>     "transaction": {
>         "id": 123456789,  <<---- This is the Vendo Transaction ID
>         "amount": "30",
>         "currency": "EUR",
>         "datetime": "2022-09-14T18:42:12+02:00"
>     },
>     "card_details": {
>         "auth_code": "123456e69c"
>     },
>     "payment_details_token": "xyzxyzxyzxyzxyzxyzxyz",
>     "request_id": "yWaYwAyWaYwAyWaYwAyWaYwA"
> }
> ```



ok, thank you for your detailed response.

but I think the subscription should be returned anyway because when check-in Vendo dashboard I see that  Vendo is creating a subscription for that user. even if I don't send subscription schedule
